apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact
    delete.retention.ms: 86400000
    file.delete.delay.ms: 6000000
    max.message.bytes: 