swagger: '2.0'
info:
  title: Hello
  x-ibm-name: hello
  version: 1.0.1
host: $(catalog.host)
schemes:
  - https
basePath: /v1/class
produces:
  - application/xml
  - application/json
consumes:
  - application/json
security: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    backend:
      value: 'https://default/'
      description: ''
      encoded: false
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  catalogs:
    Sandbox:
      properties:
        backend: 'https://test/'
  cors:
    enabled: true
  application-authentication:
    certificate: false
  assembly:
    execute:
      - gatewayscript:
          title: setResponse
          version: 1.0.0
          source: |-
            // Create response object 
            var rspObj = {
            "message" : "Hello World!"
            }

            // Save the output
            apim.setvariable('message.body', rspObj );
    catch: []
  gateway: datapower-gateway
  type: rest
tags:
  - name: artificial
    description: artificial
paths:
  /getData:
    get:
      responses:
        '200':
          description: 200 OK
    parameters: []
